dist: trusty
sudo: required

branches:
  only:
    - master

language: node_js
node_js:
  - "node"

before_install:
- sudo add-apt-repository -y ppa:mc3man/trusty-media
- sudo apt-get -qq update
- sudo apt-get install -y ffmpeg

script:
- yarn apng
- yarn build

deploy:
  provider: pages
  repo: NESTetrisJP/nestetrisjp.github.io
  target_branch: master
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public/
  on:
    branch: master
