name: Deploy (Staging)

on:
  push:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: FedericoCarboni/setup-ffmpeg@v1
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
        cache: 'yarn'
    - uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "^url: https://nestetrisjp\\.github\\.io$"
        replace: "url: https://nestetrisjp.github.io/staging-website"
        include: "_config.yml"
    - uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "^root: /$"
        replace: "root: /staging-website/"
        include: "_config.yml"
    - run: yarn install
    - run: yarn run apng
    - run: yarn run build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        repo: NESTetrisJP/staging-website
        keep_history: true
        build_dir: public/
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
