name: Deploy (Staging)

on:
  push:
    branches: [ staging ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: FedericoCarboni/setup-ffmpeg@v1
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: node ./.github/workflows/staging-config-replacement.js
    - run: npm install
    - run: npm run apng
    - run: npm run build
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.5.0
      with:
        repo: NESTetrisJP/staging-website
        keep_history: true
        build_dir: public/
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
