name: Deploy (Staging)

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: FedericoCarboni/setup-ffmpeg@v2
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: node ./.github/workflows/staging-config-replacement.js
    - run: npm install
    - run: npm run build-apng
    - run: npm run build
    - uses: crazy-max/ghaction-github-pages@v3
      with:
        repo: NESTetrisJP/staging-website
        keep_history: true
        build_dir: public/
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
